#
# helix configuration for local development
#

# title of this project. not really needed
title: 'Example Annual Report'

# Specifies the git url to the content repository. helix will use the local directory if
# not configured.
#
#content: https://github.com/namics/helix-example-report-content.git

# specifies the directory index
directoryIndex: index.html

# location of the webroot
staticRoot: /webroot